# Generated by Django 5.0.6 on 2024-06-24 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='uname',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='app.users'),
            preserve_default=False,
        ),
    ]
